{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<ipython-input-40-37d028646455>:21: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  polygon(screen, green, [(x,y), (x+44/k,y),\n",
      "<ipython-input-40-37d028646455>:23: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  polygon(screen, green, [(x,y-160/k), (x+44/k,y-160/k),\n",
      "<ipython-input-40-37d028646455>:25: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  polygon(screen, green, [(x+42/k,y-435/k), (x+72/k, y-435/k),\n",
      "<ipython-input-40-37d028646455>:27: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  polygon(screen, green, [(x+92/k,y-505/k), (x+112/k, y-505/k),\n",
      "<ipython-input-40-37d028646455>:42: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surface1 = pygame.Surface([100/k,100/k], pygame.SRCALPHA, 32)\n",
      "<ipython-input-40-37d028646455>:45: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  ellipse = pygame.draw.ellipse(surface1, green, (0, 0, 15/k, 55/k))\n",
      "<ipython-input-40-37d028646455>:47: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  screen.blit(surface2, (x+a/k, y+b/k))\n",
      "<ipython-input-40-37d028646455>:75: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  ellipse = pygame.draw.ellipse(screen, white, (x, y, 300/k, 200/k))\n",
      "<ipython-input-40-37d028646455>:78: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf1 = pygame.Surface((500/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:79: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf2 = pygame.Surface((500/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:80: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf1, black, (0/k, 75/k, 200/k, 400/k))\n",
      "<ipython-input-40-37d028646455>:81: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf2, black, (10/k, 0/k, 200/k, 90/k))\n",
      "<ipython-input-40-37d028646455>:85: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  screen.blit(surf3,(x+130/k,y-160/k))\n",
      "<ipython-input-40-37d028646455>:86: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  polygon(screen, black, [(x+70/k,y+250/k), (x+170/k,y+20/k),\n",
      "<ipython-input-40-37d028646455>:90: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf1 = pygame.Surface((500/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:91: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf2 = pygame.Surface((500/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:92: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf1, black, (0/k, 0/k, 200/k, 400/k))\n",
      "<ipython-input-40-37d028646455>:93: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf2, black, (120/k, 0/k, 200/k, 80/k))\n",
      "<ipython-input-40-37d028646455>:97: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  screen.blit(surf3,(x-88/k,y+42/k))\n",
      "<ipython-input-40-37d028646455>:100: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf1 = pygame.Surface((700/k, 800/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:101: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf2 = pygame.Surface((700/k, 800/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:102: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf1, black, (0/k, 0/k, 200/k, 400/k))\n",
      "<ipython-input-40-37d028646455>:103: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf2, black, (150/k, 480/k, 80/k, 200/k))\n",
      "<ipython-input-40-37d028646455>:107: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  screen.blit(surf3,(x-200/k,y-450/k))\n",
      "<ipython-input-40-37d028646455>:108: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  polygon(screen, black, [(x+31/k,y+238/k), (x+65/k,y+210/k),\n",
      "<ipython-input-40-37d028646455>:111: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf1 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:112: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf2 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:113: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf1, white, (0/k, 0/k, 210/k, 280/k))\n",
      "<ipython-input-40-37d028646455>:114: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf2, white, (0/k, 70/k, 280/k, 210/k))\n",
      "<ipython-input-40-37d028646455>:117: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  screen.blit(surf,(x-110/k, y-240/k))\n",
      "<ipython-input-40-37d028646455>:120: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf1 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:121: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf2 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:122: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf1, black, (0/k, 0/k, 50/k, 100/k))\n",
      "<ipython-input-40-37d028646455>:123: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf2, black, (10/k, 90/k, 50/k, 100/k))\n",
      "<ipython-input-40-37d028646455>:127: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  screen.blit(surf3,(x+120/k, y-120/k))\n",
      "<ipython-input-40-37d028646455>:129: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf1 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:130: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  surf2 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
      "<ipython-input-40-37d028646455>:131: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf1, black, (0/k, 0/k, 50/k, 100/k))\n",
      "<ipython-input-40-37d028646455>:132: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(surf2, black, (10/k, 90/k, 50/k, 100/k))\n",
      "<ipython-input-40-37d028646455>:137: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  screen.blit(surf5,(x-372/k, y-134/k))\n",
      "<ipython-input-40-37d028646455>:140: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(screen, black, (x+25/k, y+130/k, 60/k, 40/k))\n",
      "<ipython-input-40-37d028646455>:141: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(screen, black, (x+70/k, y+50/k, 60/k, 60/k))\n",
      "<ipython-input-40-37d028646455>:142: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.\n",
      "  pygame.draw.ellipse(screen, black, (x-10/k, y+25/k, 50/k, 60/k))\n"
     ]
    }
   ],
   "source": [
    "\n",
    "import pygame, sys\n",
    "from pygame.draw import *\n",
    "\n",
    "FPS = 30\n",
    "screen = pygame.display.set_mode((1400, 1000))\n",
    "screen.fill((255, 160, 122))\n",
    " \n",
    "black=(0,0,0)\n",
    "white=(255,255,255)\n",
    "green=(0,100,0)\n",
    "  \n",
    "#k - масштабный фактор\n",
    "#x,y - координаты бамбука\n",
    "\n",
    "\n",
    "    \n",
    "def bambuk(x,y,k):\n",
    "    \n",
    "    #стебль(центральный)\n",
    "    \n",
    "        polygon(screen, green, [(x,y), (x+44/k,y),\n",
    "                                (x+44/k,y-150/k), (x,y-150/k)]),\n",
    "        polygon(screen, green, [(x,y-160/k), (x+44/k,y-160/k),\n",
    "                                (x+44/k,y-310/k), (x,y-310/k)])\n",
    "        polygon(screen, green, [(x+42/k,y-435/k), (x+72/k, y-435/k),\n",
    "                                (x+37/k,y-320/k), (x+7/k,y-320/k)])\n",
    "        polygon(screen, green, [(x+92/k,y-505/k), (x+112/k, y-505/k),\n",
    "                                (x+67/k,y-445/k), (x+47/k,y-445/k)])\n",
    "   \n",
    "    #ветки\n",
    "        pygame.draw.arc(screen, green, (int(x+52/k), int(y-385/k), int(200/k), int(250/k)), 1, 3.14, int(4/k))\n",
    "        pygame.draw.arc(screen, green, (int(x+82/k), int(y-505/k), int(400/k), int(150/k)), 1.6, 3.14, int(4/k))   \n",
    "        pygame.draw.arc(screen, green, (int(x-208/k), int(y-305/k), int(200/k), int(250/k)), 0, 2, int(4/k))\n",
    "        pygame.draw.arc(screen, green, (int(x-378/k), int(y-485/k), int(401/k), int(150/k)), 0, 1.6 , int(4/k))\n",
    "    \n",
    "    #листочки\n",
    "        #листочек\n",
    "        def list(a,b,k,o):\n",
    "            #o - угол поворота листочка\n",
    "            #а - координата относительно x\n",
    "            #b - координата относительно y\n",
    "            surface1 = pygame.Surface([100/k,100/k], pygame.SRCALPHA, 32)\n",
    "            surface1 = surface1.convert_alpha()\n",
    "            surface2 = pygame.transform.rotate(surface1, o)\n",
    "            ellipse = pygame.draw.ellipse(surface1, green, (0, 0, 15/k, 55/k))\n",
    "            surface2 = pygame.transform.rotate(surface1, o)\n",
    "            screen.blit(surface2, (x+a/k, y+b/k))\n",
    "    \n",
    "    \n",
    "        #верхняя левая веточка\n",
    "        for i in range(0,5,1):\n",
    "            a = [-158, -120, -88, -183,-50]\n",
    "            b = [-480, -477, -470, -485, -455]\n",
    "            list(a[i],b[i],k,-15)\n",
    "    \n",
    "        #правая верхняя ветка\n",
    "        for i in range(0,5,1):\n",
    "            a = [112, 162, 192, 222, 252]\n",
    "            b = [-493, -515, -517, -524, -526]\n",
    "            list(a[i],b[i],k,15)\n",
    "            \n",
    "        #правая нижняя ветка\n",
    "        for i in range(0,3,1):\n",
    "            a = [102, 122,142, -58]\n",
    "            b = [-395, -405, -408]\n",
    "            list(a[i],b[i],k,15)\n",
    "        #левая нижняя ветка\n",
    "        for i in range(0,3,1):\n",
    "            a = [-58, -98, -148]\n",
    "            b = [-253, -295, -306]\n",
    "            list(a[i],b[i],k,-15)\n",
    "def panda(x,y,k):\n",
    "   \n",
    "    #Туловище\n",
    "    ellipse = pygame.draw.ellipse(screen, white, (x, y, 300/k, 200/k))\n",
    "    \n",
    "    #Средняя лапка\n",
    "    surf1 = pygame.Surface((500/k, 500/k), pygame.SRCALPHA)\n",
    "    surf2 = pygame.Surface((500/k, 500/k), pygame.SRCALPHA)\n",
    "    pygame.draw.ellipse(surf1, black, (0/k, 75/k, 200/k, 400/k))\n",
    "    pygame.draw.ellipse(surf2, black, (10/k, 0/k, 200/k, 90/k))\n",
    "    surf3 = pygame.transform.rotate(surf1, 0)\n",
    "    surf4 = pygame.transform.rotate(surf2, 60)\n",
    "    surf3.blit(surf4, (0, 0), special_flags = pygame.BLEND_RGBA_MIN)\n",
    "    screen.blit(surf3,(x+130/k,y-160/k))\n",
    "    polygon(screen, black, [(x+70/k,y+250/k), (x+170/k,y+20/k),\n",
    "                              (x+170/k,y+190/k), (x+130/k,y+280/k),(x+70/k,y+300/k)])\n",
    "    \n",
    "    #Правая лапка\n",
    "    surf1 = pygame.Surface((500/k, 500/k), pygame.SRCALPHA)\n",
    "    surf2 = pygame.Surface((500/k, 500/k), pygame.SRCALPHA)\n",
    "    pygame.draw.ellipse(surf1, black, (0/k, 0/k, 200/k, 400/k))\n",
    "    pygame.draw.ellipse(surf2, black, (120/k, 0/k, 200/k, 80/k))\n",
    "    surf3 = pygame.transform.rotate(surf1, 20)\n",
    "    surf4 = pygame.transform.rotate(surf2, 35)\n",
    "    surf3.blit(surf4, (0, 0), special_flags = pygame.BLEND_RGBA_MIN)\n",
    "    screen.blit(surf3,(x-88/k,y+42/k))\n",
    "    \n",
    "    #Левая лапка\n",
    "    surf1 = pygame.Surface((700/k, 800/k), pygame.SRCALPHA)\n",
    "    surf2 = pygame.Surface((700/k, 800/k), pygame.SRCALPHA)\n",
    "    pygame.draw.ellipse(surf1, black, (0/k, 0/k, 200/k, 400/k))\n",
    "    pygame.draw.ellipse(surf2, black, (150/k, 480/k, 80/k, 200/k))\n",
    "    surf3 = pygame.transform.rotate(surf1, 40)\n",
    "    surf4 = pygame.transform.rotate(surf2, -10)\n",
    "    surf3.blit(surf4, (0, 0), special_flags = pygame.BLEND_RGBA_MIN)\n",
    "    screen.blit(surf3,(x-200/k,y-450/k))\n",
    "    polygon(screen, black, [(x+31/k,y+238/k), (x+65/k,y+210/k),\n",
    "                                  (x+65/k,y+100/k)])\n",
    "    #Голова\n",
    "    surf1 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
    "    surf2 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
    "    pygame.draw.ellipse(surf1, white, (0/k, 0/k, 210/k, 280/k))\n",
    "    pygame.draw.ellipse(surf2, white, (0/k, 70/k, 280/k, 210/k))\n",
    "    surf1.blit(surf2, (0, 0), special_flags = pygame.BLEND_RGBA_MIN)\n",
    "    surf = pygame.transform.rotate(surf1,30)\n",
    "    screen.blit(surf,(x-110/k, y-240/k))\n",
    "    \n",
    "    #Уши\n",
    "    surf1 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
    "    surf2 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
    "    pygame.draw.ellipse(surf1, black, (0/k, 0/k, 50/k, 100/k))\n",
    "    pygame.draw.ellipse(surf2, black, (10/k, 90/k, 50/k, 100/k))\n",
    "    surf3 = pygame.transform.rotate(surf1,15)\n",
    "    surf4 = pygame.transform.rotate(surf2, 0)\n",
    "    surf3.blit(surf4, (0, 0), special_flags = pygame.BLEND_RGBA_MIN)\n",
    "    screen.blit(surf3,(x+120/k, y-120/k))\n",
    "   \n",
    "    surf1 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
    "    surf2 = pygame.Surface((400/k, 500/k), pygame.SRCALPHA)\n",
    "    pygame.draw.ellipse(surf1, black, (0/k, 0/k, 50/k, 100/k))\n",
    "    pygame.draw.ellipse(surf2, black, (10/k, 90/k, 50/k, 100/k))\n",
    "    surf3 = pygame.transform.rotate(surf1,15)\n",
    "    surf4 = pygame.transform.rotate(surf2, 0)\n",
    "    surf3.blit(surf4, (0, 0), special_flags = pygame.BLEND_RGBA_MIN)\n",
    "    surf5 = pygame.transform.rotate(surf3, -60)\n",
    "    screen.blit(surf5,(x-372/k, y-134/k))\n",
    "    \n",
    "    #Нос и глаза\n",
    "    pygame.draw.ellipse(screen, black, (x+25/k, y+130/k, 60/k, 40/k))\n",
    "    pygame.draw.ellipse(screen, black, (x+70/k, y+50/k, 60/k, 60/k))\n",
    "    pygame.draw.ellipse(screen, black, (x-10/k, y+25/k, 50/k, 60/k))\n",
    "    \n",
    "    \n",
    "#большой бамбук\n",
    "bambuk(800,680,0.8)\n",
    "#детеныш\n",
    "panda(640,730,1.3)\n",
    "#панда\n",
    "panda(920,600,0.9)\n",
    "#бамбуки поменьше\n",
    "bambuk(200,700,0.9)\n",
    "bambuk(500,820,1.15)\n",
    "bambuk(1150,590,1.3)\n",
    "                                    \n",
    "pygame.display.update()\n",
    "clock = pygame.time.Clock()\n",
    "finished = False\n",
    "    \n",
    "while not finished:\n",
    "    clock.tick(FPS)\n",
    "    for event in pygame.event.get():\n",
    "        if event.type == pygame.QUIT:\n",
    "            finished = True\n",
    "\n",
    "pygame.quit()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
